config/routes.rb
Rails.application.routes.draw do
  
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  	root to: "conversations#index"
    get "help" => "home#help"
    get "download_institute_data_template" => "home#download_institute_data_template"
  
  	devise_for :users, controllers: { sessions: 'my_devise/sessions', registrations: 'my_devise/registrations', omniauth_callbacks: 'my_devise/omniauth_callbacks', passwords: 'my_devise/passwords', unlocks: 'my_devise/unlocks' }
    
  	resources :users do
  		member do 
  			get :complete_registration 
  			post :complete_registration 
  		end	
  	end
  	
  	resources :institutes do
  		member do
  			get "add_new_member"
  			post "add_new_member"
        
        get "add_new_student"
        post "add_new_student"

        get "add_new_parent"
        post "add_new_parent"

        get "add_new_teacher"
        post "add_new_teacher"

        get "add_new_staff"
        post "add_new_staff"

        get "give_admin_right"
        post "give_admin_right"

        get "revoke_admin_right"
        post "revoke_admin_right"
  		end

      resources :events

      resources :timetable_slots

      resources :notices

      resources :attendance_records do
        collection do
          get "section_attendance_record_form"
        end
      end

      resources :grades do
        collection do
          get "add_new_grade"
          post "add_new_grade"
        end
        resources :sections do
          collection do
            get "add_new_section"
            post "add_new_section"
          end

          member do 
            get "set_classteacher"
            post "set_classteacher"
          end 

          resources :subjects do
            collection do
              get "add_new_subject"
              post "add_new_subject"
            end 

            member do 
              get "set_subject_teacher"
              post "set_subject_teacher"
            end 
          end

        end
      end
  	end

    resources :conversations do
      resources :messages do
        member do
          post "set_seen_user_id"
          get "seen_by_users"

          post "set_acted_user_ids"
          get "acted_by_users"
        end
      end
      member do
        get "remove_participants"
        post "remove_participants"
        post "add_message_category"
        delete "delete_message_category"
      end

      collection do
        get "new_group"
        post "new_group"
        get "homework"
      end  
    end

    resources :attachments do
      member do
        get "download"
      end
    end

  	resources :android_devices
    resources :ios_devices
    resources :web_notification_subscriptions
    resources :apple_web_notification_subscriptions

    scope format: false, constraints: {website_push_id: /[a-zA-Z0-9\._-]+/} do
    	post '/:version/pushPackages/:website_push_id' => 'safari_web_push#send_push_package'
	    post '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#register_device'
	    delete '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#unregister_device'
	    post '/:version/log' => 'safari_web_push#log'
	  end

    mount ActionCable.server => '/cable'
   	
end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :message_creator, class_name: "User", foreign_key: :creator_id ,inverse_of: :created_messages
	
	belongs_to :conversation, class_name: "Conversation", foreign_key: :conversation_id, inverse_of: :messages
	
	has_many :attachments, class_name: :Attachment, dependent: :destroy, as: :attachable
		
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def create
		@conversation = Conversation.find_by(id: params[:conversation_id])
		@new_message = @conversation.messages.create(content: params[:content], category: params[:message_category], creator_id: current_user.id)
		
		attached_files = params[:attached_files]
		if (!attached_files.blank?)
			attached_files.each do |file|
				new_attachment = @new_message.attachments.new()
				new_attachment.media = file

				if(!params[:attachment_category].blank?)
					new_attachment.category = params[:attachment_category] 
					if( "Image, Video, Link".include?(params[:attachment_category]) )
						@conversation.message_categories = "" if @conversation.message_categories.blank?
						if(!@conversation.message_categories.include?(params[:message_category]))
							@new_message.update(category: "Media")	
						end
					else	
						@new_message.update(category: params[:attachment_category])	if @new_message.category != params[:attachment_category]
					end	
				end

				new_attachment.save
			end
		end
		
		@conversation.update_attributes(updated_at: @new_message.created_at, last_message_id: @new_message.id)

		#publish_message_on_android_notification(@new_message, @conversation)
	end

	def set_seen_user_id
		message_id = params[:id]
		message = Message.find_by(id: message_id)
		
		if(!message.blank?)
			other_participant_ids_array = message.conversation.participants.where.not(id: message.creator_id).map{|p| p.id}
			message.seen_user_ids = "" if message.seen_user_ids.blank?
			seen_user_ids_array = message.seen_user_ids.split(", ").map{|id| id.to_i}.uniq
			if(seen_user_ids_array.blank? or !seen_user_ids_array.include?(current_user.id))
				seen_user_ids_array << current_user.id
				message.seen_user_ids = seen_user_ids_array.join(", ")
				
				if(other_participant_ids_array.sort == seen_user_ids_array.sort)
					message.is_seen_by_all_participants = true
				end
				message.save
			end
			
		else
		
		end
		
		render partial: "messages/set_seen_status.js", locals: {message: message}		
	end

	def set_acted_user_ids
		message_id = params[:id]
		@message = Message.find_by(id: message_id)
		@conversation = @message.conversation
		acted_user_ids = params[:acted_user_ids]
		
		if(!@message.blank? and !@conversation.message_categories.blank? and @conversation.message_categories.include?(@message.category))
			student_participant_ids_array = @conversation.participants.where.not(id: @message.creator_id).where(role: "Student").map{|p| p.id.to_s}
			@message.acted_user_ids = "" if @message.acted_user_ids.blank?
			acted_user_ids_array = @message.acted_user_ids.split(", ").map{|id| id.to_s}.uniq
			if(!acted_user_ids.blank?)
				acted_user_ids.each do |acted_user_id|
					if(acted_user_ids_array.blank? or !acted_user_ids_array.include?(acted_user_id))
						acted_user_ids_array << acted_user_id
						@message.acted_user_ids = acted_user_ids_array.join(", ")
						
						
						
					end
							
				end
				if(student_participant_ids_array.sort == acted_user_ids_array.sort)
					@message.is_acted_by_all_participants = true
				end
				@message.save
			end
			
			
		else
		
		end
		
		render partial: "messages/set_acted_status.js", locals: {message: @message}		
	end

	def seen_by_users
		@conversation = Conversation.find_by(id: params[:conversation_id])
		@message = @conversation.messages.find_by(id: params[:id])
		@message.seen_user_ids = "" if @message.seen_user_ids.blank?
		@seen_user_ids = @message.seen_user_ids.split(", ")
		@seen_users = User.where(id: @seen_user_ids)
		render "seen_by_users"
	end

	def acted_by_users
		@conversation = Conversation.find_by(id: params[:conversation_id])
		@message = @conversation.messages.find_by(id: params[:id])
		@message.acted_user_ids = "" if @message.acted_user_ids.blank?
		acted_user_ids = @message.acted_user_ids
		acted_user_ids_array = acted_user_ids.split(", ")
		@acted_users = User.where(id: acted_user_ids_array)
		student_participant_ids_array = @conversation.participants.where.not(id: @message.creator_id).where(role: "Student").map{|p| p.id.to_s}
		pending_user_ids_array = student_participant_ids_array - acted_user_ids_array
		@pending_users = User.where(id: pending_user_ids_array)

		render "acted_by_users"
	end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_conversation_small_publication_partial.js.erb
var conversationSmallDiv = $('.conversation-small[data-conversation-id=' + '<%= conversation.id %>' + ']');
if(conversationSmallDiv.length != 0){
	conversationSmallDiv.remove();
}

<% if(conversation.is_group == false) %>
	if($('.all-small-conversations').html()){
		$('.all-small-conversations').prepend('<%= conversation_small_partial %>');		
		var unreadConversationIdsArray = $('.unread-conversation-ids').html().split(", ");
		if(unreadConversationIdsArray.indexOf("<%= conversation.id %>") < 0){
			conversationNoDiv = $('.unread-conversation-no');
			conversationNo = parseInt(conversationNoDiv.html());
			conversationNo++;
			conversationNoDiv.html(conversationNo);
			$('.unread-conversation-ids').html($('.unread-conversation-ids').html() + ", <%= conversation.id %>");
			conversationNoDiv.css("display", "inline-block");
		}	
	}
<% else %>
	if($('.all-group-small-conversations').html()){
		if($('.all-group-small-conversations').find(".new-group-button").html()){
			$('.all-group-small-conversations').find('.clearfix').after('<%= conversation_small_partial %>');	
		}else{
			$('.all-group-small-conversations').prepend('<%= conversation_small_partial %>');		
		}
		
		var unreadConversationIdsArray = $('.unread-group-conversation-ids').html().split(", ");
		if(unreadConversationIdsArray.indexOf("<%= conversation.id %>") < 0){
			conversationNoDiv = $('.unread-group-conversation-no');
			conversationNo = parseInt(conversationNoDiv.html());
			conversationNo++;
			conversationNoDiv.html(conversationNo);
			$('.unread-group-conversation-ids').html($('.unread-group-conversation-ids').html() + ", <%= conversation.id %>");
			conversationNoDiv.css("display", "inline-block");
		}	
	}
<% end %>	

app/views/messages/_destroy_message_publication_partial.js.erb
var conversationBigDiv = $('.conversation-big[data-conversation-id=' + '<%= conversation.id %>' + ']');
	
if(conversationBigDiv.length != 0){
	var lastmessageDiv = $('.message-div[data-message-id=' + <%= message.id %> + ']');
	if(lastmessageDiv){
		lastmessageDiv.remove();
	}

	var currentUserId = $('meta[name=current-user-id]').attr("content");
	var message_creator_id = "<%= message.creator_id %>";

	if(currentUserId == message_creator_id){
		Turbolinks.visit('<%= conversation_path(conversation) %>');
	}
}

app/views/messages/_message.html.erb
<div class="messages-media message-div message" data-message-id="<%= message.id %>">
	<div class="media main-media">
		<div class="media-left pull-right">
			<a href="javascript:void(0)">
				<img src="<%= message.message_creator.profile_picture.media.url(:thumb) %>" class="img-circle img-xs">
			</a>
		</div>
		<div class="media-body media-middle">
			<h5 class="media-heading text-muted"><%= message.message_creator.first_name %><span class="pull-right"><%= get_am_pm_time(message.created_at) %>, <%= get_month_date_year(message.created_at) %></span></h5>
			<span class="pull-left"><%= message.message_creator.details %></span>
			
			<% if (message.creator_id == current_user.id or current_user.role=="Institute Admin" or current_user.role=="Principal")%>
			
				<% participant_ids_array = conversation.participants.where.not(id: message.creator_id).map{|participant| participant.id } %>
				<% message.seen_user_ids = "" if message.seen_user_ids.blank? %>
				<% seen_user_ids_array = message.seen_user_ids.split(", ").map{|id| id.to_i}.uniq %>
				<% if(message.is_seen_by_all_participants == true) %>
					<span class="double-checkmark pull-right" data-message-id=<%= message.id %> data-conversation-id=<%= conversation.id %>> &nbsp;<a>Seen by all</a></span>
				<% else %>
					<span class="double-checkmark pull-right" data-message-id=<%= message.id %> data-conversation-id=<%= conversation.id %>>&nbsp;<a>Seen by </a><%= seen_user_ids_array.length %></span>
				<% end %>
			<% end %>
			<% if((message.creator_id == current_user.id or current_user.role=="Institute Admin"  or current_user.role=="Principal") and !conversation.message_categories.blank? and conversation.message_categories.include?(message.category)) %>
					
				<% student_participant_ids_array = conversation.participants.where.not(id: message.creator_id).where(role: "Student").map{|p| p.id} %>
				<% message.acted_user_ids = "" if message.acted_user_ids.blank? %>
				<% acted_user_ids_array = message.acted_user_ids.split(", ").map{|id| id.to_i}.uniq %>
				<% if(message.is_acted_by_all_participants == true) %>
					<span class="checkmark pull-right" data-message-id=<%= message.id %> data-conversation-id=<%= conversation.id %>><a>Submitted by all</a></span>
				<% else %>
					<span class="checkmark pull-right" data-message-id=<%= message.id %> data-conversation-id=<%= conversation.id %>><a>Submitted by</a> <%= acted_user_ids_array.length %></span>
				<% end %>
			<% end %>

			<% if((current_user.role == "Student" or current_user.role == "Parent") and message.creator_id != current_user.id and !conversation.message_categories.blank? and conversation.message_categories.include?(message.category)) %>
					
				<% message.acted_user_ids = "" if message.acted_user_ids.blank? %>
				<% acted_user_ids_array = message.acted_user_ids.split(", ").map{|id| id.to_i}.uniq %>
				<% if(acted_user_ids_array.include?(current_user.id) or (!current_user.child_ids.blank? and acted_user_ids_array.include?(current_user.child_ids.split(", ")))) %>
					<span class="checkmark pull-right" data-message-id=<%= message.id %> data-conversation-id=<%= conversation.id %>>Submitted</span>
				<% else %>
					<span class="checkmark pull-right" data-message-id=<%= message.id %> data-conversation-id=<%= conversation.id %>>Pending</span>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="media-content text-muted show-message-body">
		<%= message.content %>
	</div>					
	<% if(!message.attachments.blank?) %>
		<% message.attachments.each do |attachment| %>
			<div class="text-center" style="max-width: 300px; margin: 3px auto; ">
				<% if(attachment.is_image_type?) %>
					 <% attachment_type = "Image" %>
				<% end %>
				<% if(attachment.is_document_type?) %>
					<% attachment_type = "Document" %>
				<% end %>
				<% if(attachment.is_video_type?) %>
					<% attachment_type = "Video" %>
				<% end %>
				<div class="many-type-media view-attachment-button" style="display: inline-block;" data-href="https://docs.google.com/gview?url=https://classtalk.in<%= attachment.media.url %>&embedded=true&chrome=true" data-attachment-type="<%= attachment_type %>" data-attachment-url="<%= attachment.media.url %>" data-attachment-extension="<% attachment.media_content_type %>">
					<a>
						<% if(attachment.is_image_type?) %>
							<p class="inner-many-type-media">View Image</p>
						<% end %>
						<% if(attachment.is_document_type?) %>
							<p class="inner-many-type-media">View Document</p>
						<% end %>
						<% if(attachment.is_video_type?) %>
							<p class="inner-many-type-media">View Video</p>
						<% end %>
					</a>
				</div>
				<div style="display: inline-block;">
					<%= link_to download_attachment_path(attachment), target: "_blank" do %>
						<p class="inner-many-type-media" style="padding: 7px; line-height: 1.9;"><i class="material-icons" style="color: #fff;vertical-align: middle;">&#xE884;</i></p>
					<% end %>	
				</div>
			</div>	
		<% end %>	
	<% end %>
</div>

app/views/messages/_message_seen_status_publication_partial.js.erb
var currentUserId = $('meta[name=current-user-id]').attr("content");
var message_creator_id = "<%= message.creator_id %>";
if(currentUserId == message_creator_id){
	messageDiv = $('.message-div[data-message-id=' + <%= message.id %> + ']');
	checkDiv = $(messageDiv).find(".double-checkmark");
	<% if(message.is_seen_by_all_participants == true) %>
		checkDiv.html("Seen by All");
	<% else %>
		checkDiv.html("Seen by <%=message.seen_user_ids.split(", ").count %>");	
	<% end %>
}

app/views/messages/_publish_message_partial.js.erb
var conversationBigDiv = $('.conversation-big[data-conversation-id=' + '<%= conversation.id %>' + ']');
	
if(conversationBigDiv.length != 0){
	$('.temp-message').remove();
	
	<% if(message.category == "Messages") %>
		messagesDiv =  $('.conversation-big[data-conversation-id=' + '<%= conversation.id %>' + ']').find('.Messages-category-messages');
		if(messagesDiv){
			messagesDiv.prepend('<%= j render( partial: "messages/message", locals: {conversation: conversation, message: message} ) %> ');
			$('ul.nav a[href="' + '#all-Messages' + '"]').tab('show');		
		}
	<% end %>

	<% if(!message.attachments.blank?) %>
		meediaMessagesDiv = $('.conversation-big[data-conversation-id=' + '<%= conversation.id %>' + ']').find('.Media-category-messages');
		if(meediaMessagesDiv){
			meediaMessagesDiv.prepend('<%= j render( partial: "messages/message", locals: {conversation: conversation, message: message} ) %> ');
			$('ul.nav a[href="' + '#all-Media' + '"]').tab('show');		
		}
	<% end %>	

	<% if(message.category != "Messages") %>
		categoryMessagesDiv = $('.conversation-big[data-conversation-id=' + '<%= conversation.id %>' + ']').find('.<%= message.category.split(" ").join("_") %>-category-messages');
		if(categoryMessagesDiv){
			categoryMessagesDiv.prepend('<%= j render( partial: "messages/message", locals: {conversation: conversation, message: message} ) %> ');
			$('ul.nav a[href="' + '#all-<%= message.category.split(" ").join("_")%>' + '"]').tab('show');		
		}
	<% end %>

	messageBodyDiv = $(".message-div[data-message-id='<%= message.id %>']").find(".show-message-body");
	messageBodyDiv.html($(messageBodyDiv).html().linkify());

	$(".message-div[data-message-id='<%= message.id %>'] .view-attachment-button").on("click", function(){
		$(this).html("");
		attachmentType = $(this).attr("data-attachment-type");
		if(attachmentType == "Image"){
			var linkMedia = $(this).attr("data-attachment-url");
			var markupArryForMedia=[
				'<p style="max-width: 300px; margin: 0 auto;">',
					'<img style="width: 100%;" height= "200" src="' +  linkMedia + '"></img>',
				'</p>' 
			];
		}

		if(attachmentType == "Video"){
			var linkMedia = $(this).attr("data-attachment-url");
			var fileType = $(this).attr("data-attachment-extension");
			var markupArryForMedia=[
				'<p style="max-width: 300px; margin: 0 auto;">',
					'<video width="300" height="200" controls class="video-js vjs-default-skin">',
							'<source src="' + linkMedia + '" type="' + fileType +'" >',
							
							'Your browser does not support the video tag.',
					'</video>',
				'</p>' 
			];
		}
		if(attachmentType == "Document"){
			var linkMedia = $(this).attr("data-href");
			var markupArryForMedia=[
				'<p style="max-width: 300px; margin: 0 auto;">',
					'<iframe style="width: 100%;" height= "200" src="' +  linkMedia + '"></iframe>',
				'</p>' 
			];
		}
		$(this).html(markupArryForMedia.join(''));
	});

	//App.scrollToBottomOfPage();
	
	var lastmessageDiv = $('.message-div[data-message-id=' + <%= message.id %> + ']');
	if(lastmessageDiv){
		
		var statusDiv = lastmessageDiv.find('.double-checkmark');
		var submissionDiv = lastmessageDiv.find('.checkmark');
		var currentUserId = $('meta[name=current-user-id]').attr("content");
		var message_creator_id = "<%= message.creator_id %>";
		
		if(currentUserId == message_creator_id){
			$(".double-checkmark").on("click", function(){
				var messageId = $(this).attr("data-message-id");
				$.ajax({
					url: "/conversations/<%= conversation.id %>/messages/" + messageId + "/seen_by_users.js",  
					type: "GET",
					success: function(data) {
						if(data.trim().length == 0) {
							$("#seenStatusModal").find(".modal-body").html("No one has yet seen this message !");
						} else {
							$("#seenStatusModal").find(".modal-body").html(data);
						}
					}
				});
				$("#seenStatusModal").modal('show');
			});
			$(".checkmark").on("click", function(){
				var messageId = $(this).attr("data-message-id");
				$.ajax({
					url: "/conversations/<%= @conversation.id %>/messages/" + messageId + "/acted_by_users.js",  
					type: "GET",
					success: function(data) {
						if(data.trim().length == 0) {
							$("#submissionStatusModal").find(".modal-body").html("No one has yet acted on this message !");
						} else {
							$("#submissionStatusModal").find(".modal-body").html(data);
						}
					}
				});
				$("#submissionStatusModal").modal('show');
			});
		}else{
			statusDiv.remove();
			submissionDiv.remove();
			$.ajax({
				url: "<%= set_seen_user_id_conversation_message_path(conversation, message) %>",
				type: "POST",
				beforeSend: function(data) {
					var csfrToken = $("meta[name='csrf-token']").attr("content");
					data.setRequestHeader('X-CSRF-Token', csfrToken);
				},
				success: function(data) {
					return;
				}
			});
		}
	}
	
}

app/views/messages/_set_acted_status.js.erb
messageDiv = $('.message-div[data-message-id=' + <%= @message.id %> + ']');
checkDiv = $(messageDiv).find(".checkmark");
<% if(!message.is_acted_by_all_participants == true) %>
	checkDiv.html("Submitted by All");
<% else %>
	checkDiv.html("Submitted by <%= @message.acted_user_ids.split(", ").count %>");	
<% end %>

$("#submissionStatusModal").modal('hide');

app/views/messages/_set_seen_status.js.erb
<% if(!message.blank?) %>
	<% script_string = render partial: "messages/message_seen_status_publication_partial.js", locals: {message: message} %>
	
	<% publish_to(user_path(message.message_creator), script_string) %>
		
<% end %>

app/views/messages/acted_by_users.html.erb
<div class="container-width classRoute" style="margin-bottom:85px;">	
	<ul class="nav nav-tabs text-center" role="tablist" id="tablist">		
		<li style="width:50%;"><a data-toggle="tab" href="#all-submitted-users">Submitted by</a></li>
		<li class="active" style="width:50%;"><a data-toggle="tab" href="#all-pending-users">Pending Users</a></li>
	</ul>
	<div class="tab-content admin-home-content">
		<div class="tab-pane all-small-conversations" id="all-submitted-users">
			<% if(!@acted_users.blank?) %>
				<% if(@message.creator_id == current_user.id or current_user.role.include?("Institute Admin")) %>
					<% @acted_users.each do |user| %>
						<%= render partial: "conversations/contact", locals: {contact: user} %>
					<% end %>
				<% else %>
					<% if(@acted_users.include?(current_user)) %>
						<%= render partial: "conversations/contact", locals: {contact: current_user} %>
					<% else %>
						<h1 class="nothing-posted">	No Submission from you yet ! </h1>
					<% end %>
				<% end %>
				
			<% else %>
				<h1 class="nothing-posted">	No Submission yet ! </h1>
			<% end %>

		</div>
		<div class="tab-pane active all-small-conversations" id="all-pending-users">					
			<% if(!@pending_users.blank?) %>
				<% if(@message.creator_id == current_user.id or current_user.role.include?("Institute Admin")) %>
					<%= form_tag set_acted_user_ids_conversation_message_path(@conversation, @message), method: :post, remote: true do %>
					
						<button type="submit" class="btn btn-success mar-btm" style="width: 100%;"> Mark Submission </button>

						<% @pending_users.each do |user| %>
							
								<div class="well well-sm">
									<label for="contact-new-group-<%= user.id %>-<%= user.role %>" class="modal-label"  style="vertical-align: middle;">
										<%= check_box_tag "acted_user_ids[]", user.id, false,class:"contact-new-group-page", id:"contact-new-group-#{user.id}-#{user.role}"  %>
										<div class="media jumbotron-media">
											<div class="media-left media-middle">
												
												<img src="<%= user.profile_picture.media.url(:thumb) %>" class="img-rounded img-xs">
												
											</div>
											<div class="media-body media-middle">
												<h5 class="media-heading student-name-in-message"><%= user.first_name %> <%= user.last_name %></h5>

												<small class="role-small"><%= user.details %></small>
												
											</div>				
										</div>
										<span class="uncheckbox-style-block uncheckbox-style-block-<%= user.id %>"></span>		
										<span class="checkbox-style-block checkbox-style-block-<%= user.id %>"></span>
									</label>

									
									
									
								</div>
								
							
						<% end %>
					<% end %>
				<% else %>
					<% if(@pending_users.include?(current_user)) %>
						<%= render partial: "conversations/contact", locals: {contact: current_user} %>
					<% else %>
						<h1 class="nothing-posted">	You have Submitted </h1>
					<% end %>
				<% end %>
				
			<% else %>
				<h1 class="nothing-posted"> No Pending Users </h1>	
			<% end %>
		
			
		</div>
	</div>	
</div>	

app/views/messages/create.js.erb
$("#new-message-text-field").val("");
$('.custom-file-input').val("");
$("button.close").trigger("click");
<% script_string = render partial: "messages/publish_message_partial", locals: {conversation: @conversation, message: @new_message} %>
<% publish_to(user_path(current_user), script_string) %>

<% conversation_small_partial = j render( partial: "conversations/conversation_small", locals: {conversation: @conversation, user: current_user}) %>
<% script_string = render partial: "messages/conversation_small_publication_partial", locals: {conversation: @conversation, conversation_small_partial: conversation_small_partial} %>
<% publish_to(user_path(current_user), script_string) %>

<% @conversation.other_participants(current_user).each do |participant| %>
	<% script_string = render partial: "messages/publish_message_partial", locals: {conversation: @conversation, message: @new_message} %>
	<% publish_to(user_path(participant), script_string) %>

	<% conversation_small_partial = j render( partial: "conversations/conversation_small", locals: {conversation: @conversation, user: participant}) %>
	<% script_string = render partial: "messages/conversation_small_publication_partial", locals: {conversation: @conversation, conversation_small_partial: conversation_small_partial} %>
	<% publish_to(user_path(participant), script_string) %>
<% end %>

<% publish_message_on_android_notification(@new_message, @conversation) %>

app/views/messages/destroy.js.erb
<% script_string = render partial: "messages/destroy_message_publication_partial", locals: {conversation: @conversation, message: @message} %>
<% publish_to(conversation_path(@conversation), script_string) %>

app/views/messages/seen_by_users.html.erb
<% if(!@seen_users.blank?) %>
	<ul class="list-inline">
		<% @seen_users.each do |user| %>
			<li>
				<%= render partial: "conversations/contact", locals: {contact: user} %>
			</li>			
		<% end %>
	</ul>	
<% end %>