config/routes.rb
Rails.application.routes.draw do
  
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  	root to: "conversations#index"
    get "help" => "home#help"
    get "download_institute_data_template" => "home#download_institute_data_template"
  
  	devise_for :users, controllers: { sessions: 'my_devise/sessions', registrations: 'my_devise/registrations', omniauth_callbacks: 'my_devise/omniauth_callbacks', passwords: 'my_devise/passwords', unlocks: 'my_devise/unlocks' }
    
  	resources :users do
  		member do 
  			get :complete_registration 
  			post :complete_registration 
  		end	
  	end
  	
  	resources :institutes do
  		member do
  			get "add_new_member"
  			post "add_new_member"
        
        get "add_new_student"
        post "add_new_student"

        get "add_new_parent"
        post "add_new_parent"

        get "add_new_teacher"
        post "add_new_teacher"

        get "add_new_staff"
        post "add_new_staff"

        get "give_admin_right"
        post "give_admin_right"

        get "revoke_admin_right"
        post "revoke_admin_right"
  		end

      resources :events

      resources :timetable_slots

      resources :notices

      resources :attendance_records do
        collection do
          get "section_attendance_record_form"
        end
      end

      resources :grades do
        collection do
          get "add_new_grade"
          post "add_new_grade"
        end
        resources :sections do
          collection do
            get "add_new_section"
            post "add_new_section"
          end

          member do 
            get "set_classteacher"
            post "set_classteacher"
          end 

          resources :subjects do
            collection do
              get "add_new_subject"
              post "add_new_subject"
            end 

            member do 
              get "set_subject_teacher"
              post "set_subject_teacher"
            end 
          end

        end
      end
  	end

    resources :conversations do
      resources :messages do
        member do
          post "set_seen_user_id"
          get "seen_by_users"

          post "set_acted_user_ids"
          get "acted_by_users"
        end
      end
      member do
        get "remove_participants"
        post "remove_participants"
        post "add_message_category"
        delete "delete_message_category"
      end

      collection do
        get "new_group"
        post "new_group"
        get "homework"
      end  
    end

    resources :attachments do
      member do
        get "download"
      end
    end

  	resources :android_devices
    resources :ios_devices
    resources :web_notification_subscriptions
    resources :apple_web_notification_subscriptions

    scope format: false, constraints: {website_push_id: /[a-zA-Z0-9\._-]+/} do
    	post '/:version/pushPackages/:website_push_id' => 'safari_web_push#send_push_package'
	    post '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#register_device'
	    delete '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#unregister_device'
	    post '/:version/log' => 'safari_web_push#log'
	  end

    mount ActionCable.server => '/cable'
   	
end

app/models/institute.rb
class Institute < ApplicationRecord

	belongs_to :institute_creator, class_name: :User, foreign_key: :creator_id, inverse_of: :created_institutes
	
	has_many :members, class_name: :User, through: :institutes_members, source: :member, dependent: :destroy

	has_many :institutes_members, class_name: :InstituteMember, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy
	
	has_many :grades, class_name: :Grade, through: :institutes_grades, source: :grade
	
	has_many :institutes_grades, class_name: :InstituteGrade, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy
	
	has_many :institutes_grades_sections_models, class_name: :GradeSection, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy
	
	has_many :institutes_sections_members_models, class_name: :SectionMember, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy

	has_many :institutes_sections_subjects_models, class_name: :SectionSubject, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy

	has_many :events, class_name: :Event, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy

	has_many :notices, class_name: :Notice, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy
	
	has_one :location, class_name: :Location, as: :locatable, dependent: :destroy

	has_many :attendance_records, class_name: :AttendanceRecord, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy
	
	has_many :timetable_slots, class_name: :TimetableSlot, foreign_key: :institute_id, inverse_of: :institute, dependent: :destroy

	has_one :institute_data_file, class_name: :Attachment, dependent: :destroy, as: :attachable

	def short_name
		non_text_characterless_string = self.institute_name.gsub(/[^0-9a-z ]/i, '')
		split_array = non_text_characterless_string.split(" ")
		short_name_string = ""
		split_array.first(4) do |string|
			if(string == string.upcase)
				short_name_string = short_name_string + string + " "
			else
				short_name_string = short_name_string + string[0].upcase + "."
			end
		end
		return short_name_string
	end

	def chech_if_member user_id
		return self.institutes_members.map{|structure| structure.member_id}.include?(user_id)
	end

	def add_member member_id, adder_id, role
		if(!self.chech_if_member(member_id))
			self.institutes_members.create(member_id: member_id, creator_id: adder_id, role_in_institute: role)	
		end	
	end
	
	def check_if_institute_creator member
		return self.creator_id == member.id
	end
	
	def get_membership_model member
		return self.institutes_members.find_by(member_id: member.id)
	end

	def get_members_role_in_institute member
		return self.get_membership_model(member).role_in_institute
	end

	def get_other_members_for_user user
		member_role = self.get_members_role_in_institute(user)
		if(member_role == "Student" or member_role == "Parent")
			self.get_members_with_given_roles(["Principal", "Institute Admin", "Teacher"])
		else
			self.get_members_with_given_roles(["Principal", "Institute Admin", "Teacher", "Student", "Parent"])
		end
	end
	
	def get_members_with_given_roles roles
		return self.institutes_members.where(role_in_institute: roles).map{|im| im.member}
	end

	after_create :generate_unique_institute_code
	
	def generate_unique_institute_code
		institute_name = self.institute_name
		if(self.institute_name.length < 3)
			(3 - self.institute_name.length).times do
				institute_name = institute_name + "X"
			end
		else
			institute_name = self.institute_name[0..2]
		end
		
		unique_code = "CN" + institute_name + self.id.to_s
		if(self.unique_institute_code != unique_code.upcase)
			self.unique_institute_code = unique_code.upcase
			self.save
		end
		
	end

	def delete_members
		members = self.members
		members.each do |member|
			member.destroy
		end
	end

	after_create :add_creator_as_admin
	
	def add_creator_as_admin
		self.institutes_members.create(member_id: self.creator_id, role_in_institute: "Institute Admin", creator_id: self.creator_id)
	end
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController

  before_action :set_timezone, only: [:give_admin_right, :revoke_admin_right]
  def set_timezone
      Time.zone = "New Delhi"
  end

  before_action :set_institute, except: [:index, :new, :create]
  def set_institute
    @institute = Institute.find_by(id: params[:id])
  end 
  
  def index

  end

  def new

  end

  def create

  end

  def show
      if(!@institute.blank?)
          @institute_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: nil, section_id: nil, subject_id: nil, is_custom_group: false)
          @principals = @institute.get_members_with_given_roles(["Principal"])
          @admins = @institute.members.where("role LIKE ? or role LIKE ?", "%, Institute Admin", "Institute Admin")
          @teachers = @institute.get_members_with_given_roles(["Teacher"])
          @institutes_grades_sections_models = @institute.institutes_grades_sections_models
          if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin"))
              @grades = @institute.grades
          else
              @section_member_models = current_user.members_sections
              @grades = @section_member_models.map(&:grade).uniq 
          end
      end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  def add_new_member
    if(request.get?)
      if(request.xhr?)
        render layout: false
      end
    elsif(request.post?)
      profile_picture = params[:profile_picture]
      first_name = params[:first_name]
      last_name = params[:last_name]
      isd_code = params[:isd_code]
      mobile_no = params[:mobile_no]
      email = params[:email]
      gender = params[:gender]
      role = params[:role]

      if(!@institute.blank?)
        @new_member = nil
        @new_member = User.where(email: email).first if !email.blank?
        if(@new_member.blank?)
          @new_member = User.where(isd_code: isd_code, mobile_no: mobile_no).first if !mobile_no.blank?
        end
      
        if(!@new_member.blank?)
          if(@institute.chech_if_member(@new_member))
            flash[:notice] = "#{@new_member.first_name.capitalize} is already a member of #{@institute.institute_name}."     
            redirect_to root_path
          end
          @new_member.update(role: role) if @new_member.role .blank?
        else
          password = Random.new.rand(1000..9999).to_s
          @new_member = User.new
          @new_member.password = password
          @new_member.first_name = first_name if !first_name.blank?
          @new_member.last_name = last_name if !last_name.blank?
          @new_member.isd_code = isd_code if !isd_code.blank?
          @new_member.mobile_no = mobile_no if !mobile_no.blank?
          @new_member.email = email if !email.blank?
          @new_member.gender = gender if !gender.blank?
          @new_member.role = role if !role .blank?
          @new_member.is_registration_complete = true
          @new_member.save
          save_user_password_with_system_encryption_key(@new_member, password)
          if !profile_picture.blank?
            @new_member.profile_picture.media = profile_picture 
            @new_member.save
          end  
          
          send_user_account_password_through_email(@new_member, password) if !@new_member.email.blank?
          send_user_account_password_through_sms(@new_member, password) if !@new_member.mobile_no.blank?
          
        end
        
        @institute.add_member(@new_member.id, current_user.id, role) 
        @institute_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: nil, section_id: nil, subject_id: nil, is_custom_group: false)
        @institute_conversation.add_participant(@new_member.id, current_user.id) if !@institute_conversation.blank?  

        if(role == "Principal" or role == "Institute Admin")
            grades = @institute.grades
            grades.each do |grade|
               sections = grade.sections
               sections.each do |section|
                  section.add_member_for_institute_and_grade(@institute, grade, current_user, @new_member, role)
                  section_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: nil, is_custom_group: false) 
                  section_conversation.add_participant(@new_member.id, current_user.id) if !section_conversation.blank?

                  sections_subjects = section.sections_subjects.where(institute_id: @institute.id, grade_id: grade.id)
                  sections_subjects.each do |section_subject|
                      subject_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: section_subject.subject_id, is_custom_group: false)
                      subject_conversation.add_participant(@new_member.id, current_user.id) if !subject_conversation.blank?
                  end
                end


            end
            
        end

        if((role == "Parent" or role == "Student") and !params[:student_parent_grade_name].blank? and !params[:student_parent_section_name].blank?)
          grade = @institute.grades.find_by(grade_name: params[:student_parent_grade_name])
          section = grade.get_sections_for_institute(@institute).find_by(section_name: params[:student_parent_section_name])
          section.add_member_for_institute_and_grade(@institute, grade, current_user, @new_member, role) if !section.blank?
          
          section_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: nil, is_custom_group: false)
          
          section_conversation.add_participant(@new_member.id, current_user.id) if !section_conversation.blank?

          sections_subjects = section.sections_subjects.where(institute_id: @institute.id, grade_id: grade.id)
          sections_subjects.each do |section_subject|
              subject_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: section_subject.subject_id, is_custom_group: false)
              subject_conversation.add_participant(@new_member.id, current_user.id) if !subject_conversation.blank?
          end
        end
        
        if(role == "Teacher" and !params[:classteacher_grade_name].blank? and !params[:classteacher_section_name].blank?)
          grade = @institute.grades.find_by(grade_name: params[:classteacher_grade_name])
          section = grade.get_sections_for_institute(@institute).find_by(section_name: params[:classteacher_section_name])
            
          section.add_member_for_institute_and_grade(@institute, grade, current_user, @new_member, role) if !section.blank?
          section.set_classteacher_for_institute_and_grade(@institute, grade, @new_member) if !section.blank?
          section_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: nil, is_custom_group: false) if !section.blank?
          
          section_conversation.add_participant(@new_member.id, current_user.id) if !section_conversation.blank? if !section.blank?
            
          
        end
        
        if(role == "Teacher" and !params[:grades].blank?)
          params[:grades].each do |grade_name, grade_extras|
            grade = @institute.grades.find_by(grade_name: grade_name)
            grade_extras[:section_names].each do |section_name|
              section = grade.get_sections_for_institute(@institute).find_by(section_name: section_name) if !grade.blank?
              
              grade_extras[:subject_names].each do |subject_name|
                subject = section.get_subjects_for_institute_and_grade(@institute, grade).find_by(subject_name: subject_name) if !section.blank?
                section.set_subject_teacher_for_institute_and_grade_and_subject(@institute, grade, subject, @new_member) if !section.blank?

                subject_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: subject.id, is_custom_group: false)
                subject_conversation.add_participant(@new_member.id, current_user.id) if !subject_conversation.blank?
              end
              
              section_conversation = Conversation.find_by(institute_id: @institute.id, grade_id: grade.id, section_id: section.id, subject_id: nil) if !section.blank?
              section_conversation.add_participant(@new_member.id, current_user.id) if !section_conversation.blank?
              
            end
          end
        end
        flash[:notice] = "Successfully added #{@new_member.first_name} to #{@institute.institute_name} as #{role}."     
        redirect_to root_path
        
      end
    end    
  end

  def add_new_student
    if(request.get?)
        @institutes_grades_sections_models = @institute.institutes_grades_sections_models
        @grades = @institutes_grades_sections_models.map(&:grade).uniq
        @sections = @institutes_grades_sections_models.map(&:section).uniq

        render "add_new_student_step_1"
    end

    if(request.post?)
        if(!params[:step].blank? and params[:step].to_i == 1)
            @student = nil
            if(!params[:email].blank?)
                @student = User.find_by(email: params[:email])
            end
            if(@student.blank? and !params[:mobile_no].blank?)
                @student = User.find_by(mobile_no: params[:mobile_no])
            end
            if(@student.blank?)
                password = Random.new.rand(1000..9999).to_s
                @student = User.new(role: "Student")
                @student.password = password
                @student.first_name = params[:first_name] if !params[:first_name].blank?
                @student.last_name = params[:last_name] if !params[:last_name].blank?

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/add_new_parent.js.erb
alert("new parent added successfully");
$('.new-parent-step-2-form-div').remove();

var animateNextPage = $(".new-parent-step-1-form-div");

$(animateNextPage).stop().animate({
    "left": "0px"
}, 500, function(){$(animateNextPage).css("display", "block");});

app/views/institutes/add_new_parent_step_1.js.erb
$('#new-parent-form')[0].reset();
var animateNextPage = $(".new-parent-step-1-form-div");

$(animateNextPage).stop().animate({
    "left": "-1100px"
}, 500, function(){$(animateNextPage).css("display", "none");});

if($('.new-parent-step-2-form-div').html()){
	$('.new-parent-step-2-form-div').remove();
}
$('.new-parent-step-1-form-div').after('<%= j render "add_new_parent_step_2.html" %>');

app/views/institutes/add_new_staff.js.erb
alert("new <%= @staff.role %> added successfully");
$('.new-staff-step-2-form-div').remove();
$('.new-staff-step-1-form-div').show();

app/views/institutes/create.html.erb
<h1>Institutes#create</h1>
<p>Find me in app/views/institutes/create.html.erb</p>

app/views/institutes/show.html.erb
<% content_for :heading do %>
	<a class="mybtn btn btn-link btn-xs pull-left" href="/">
		<i class="material-icons">&#xE88A;</i>			
	</a>
	<% if(current_user.role.include?("Institute Admin") or current_user.role.include?("Principal")) %>
		Manage Institute
	<% else %>
		My Institute
	<% end %>
<% end %>

<div class="container-width classRoute tabs-container" style="margin-top:50px; margin-bottom: 0;">
	<ul class="nav nav-tabs admin-new-tabs" role="tablist" id="tablist">
		<li class="active"><a data-toggle="tab" href="#all-admins">Admins</a></li>
		<li><a data-toggle="tab" href="#all-teachers">Teachers</a></li>
		<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin") or current_user.role.include?("Teacher")) %>
			<li><a data-toggle="tab" href="#all-students">Students</a></li>	
		<% end %>
		<li><a data-toggle="tab" href="#all-classes">Classes</a></li>
	</ul>
	<div class="tab-content" style="max-width: 600px; margin: 0 auto; margin-bottom: 70px">
		<div class="tab-pane active" id="all-admins" style="max-height: 100%;">
			<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
				
				<div class="max-width-button">
					<%= link_to give_admin_right_institute_path(@institute) do %>
						<div class="pull-right add-member">
							<span>Give Admin Rights</span><i class="material-icons">&#xE7FE;</i>
						</div>
					<% end %>
					<%= link_to add_new_staff_institute_path(@institute, role: "Institute Admin") do %>
						<div class="pull-right add-member">
							<span>Add Admin</span><i class="material-icons">&#xE7FE;</i>
						</div>
					<% end %>
				</div>	

				<%= link_to revoke_admin_right_institute_path(@institute) do %>
					<div class="pull-right add-member add-revoke-rights">
						<span>Revoke Admin Rights</span><i class="material-icons">&#xE7FE;</i>
					</div>
				<% end %>
				<form onsubmit="return false;" class="search-form-main">
					<div class="pull-left form-group has-feedback" style="width:100%;margin-top: 8px;">
						<input type="text" class="form-control search-conversation-admin-page" name="search" placeholder="Search..." id="search1" autocomplete="off">
					</div>
				</form>
			<% end %>
			<div class="clearfix mar-btm"></div>
			
			<% if(!@admins.blank?) %>
				<div class="admin-manage-page">
					<% @admins.each do |admin| %>
						<%= render partial: "conversations/contact", locals: {contact: admin}	 %>	
					<% end %>
				</div>	
			<% else %>	
				<h1 class="nothing-posted"> No Admins added yet ! </h1>		
			<% end %>
		</div>
	
		<div class="tab-pane" id="all-teachers" style="max-height: 100%;">
			<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
				
				<%= link_to add_new_staff_institute_path(@institute, role: "Teacher") do %>
					<div class="pull-right add-member">
						<span>Add Teacher</span><i class="material-icons">&#xE7FE;</i>
					</div>
				<% end %>
				<div class="clearfix"></div>
				<form onsubmit="return false;" class="search-form-main">
					<div class="pull-left form-group has-feedback" style="margin-top: 8px; width: 100%;">
						<input type="text" class="form-control search-conversation-teacher-page" name="search" placeholder="Search..." id="search1" autocomplete="off">
					</div>
				</form>
			<% end %>
			<div class="clearfix mar-btm"></div>
			<% if(!@teachers.blank?) %>
				<div class="teacher-manage-page">
					<% @teachers.each do |contact| %>
						<%= render partial: "conversations/contact", locals: {contact: contact}	 %>	
					<% end %>
				</div>	
			<% else %>	
				<h1 class="nothing-posted"> No Teachers added yet ! </h1>			
			<% end %>
		</div>

		<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin") or current_user.role.include?("Teacher")) %>
			<div class="tab-pane" id="all-students" style="max-height: 100%;">
				<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
					
					<%= link_to add_new_student_institute_path(@institute) do %>
						<div class="pull-right add-member">
							<span>Add Student</span><i class="material-icons">&#xE7FE;</i>
						</div>
					<% end %>
					<div class="clearfix"></div>
					<form onsubmit="return false;" class="search-form-main">
						<div class="pull-left form-group has-feedback" style="width: 100%;margin-top: 8px;">
							<input type="text" class="form-control search-conversation-student-page" name="search" placeholder="Search..." id="search1" autocomplete="off">
						</div>
					</form>
				<% end %>
				<div class="clearfix mar-btm"></div>
				<ul class="list-unstyled index-conversation-modal">
					<% if(!@institutes_grades_sections_models.blank?) %>
						<% @institutes_grades_sections_models.each do |grade_section_model|%>
							<% grade = grade_section_model.grade %>
							<% section = grade_section_model.section %>
							<% students = section.get_members_with_given_roles_for_institute_and_grade_with_role(@institute, grade, ["Student"]) %>
							<li class="find-teacher-list find-tab-teacher-list" style="margin-bottom:10px;position:relative;">
								
								<h6 class="teachers-list-heading-inner" style="background: #d1cece;margin: 0;padding: 10px; color: #dd223d;">
									<%= grade.custom_name_for_institute(@institute) + " " + section.section_name %>																		
									<i class="material-icons arrow-up-icon pull-right" style="margin-top:-5px;">&#xE316;</i>
								</h6>
								<div class="container-width classRoute class-tab-students-list-custom" style="display: none; box-shadow:rgb(175, 172, 172) 1px 1px 10px;margin-bottom:10px;">
									
									<ul class="list-unstyled index-conversation-modal student-manage-page" style="box-shadow: none;    max-height: 200px !important;">
										<% if(!students.blank?) %>
											<% students.each do |student| %>
												<% if(student.id != current_user.id) %>
													<li>
															
														<%= render partial: "conversations/contact", locals: {contact: student} %>
															
													</li>
												<% end %>	
											<% end %>
										<% else %>
											<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
												<%= link_to add_new_student_institute_path(@institute, role: "Teacher") do %>
													<div class="pull-right add-member">
														<span>Add Student</span><i class="material-icons">&#xE7FE;</i>
													</div>
												<% end %>
												<div class="clearfix"></div>
												<h1 class="nothing-posted"> No Students added yet ! </h1>	
											<% end %>
											
										<% end %>															
									</ul>
								</div>
							</li>
						<% end %>
					<% else %>
						<div class="nothing-posted"> No Classes Added yet ! Add Classes First ! </div>
					<% end %>				
				</ul>

			</div>
			
		<% end %>

		<div class="tab-pane" id="all-classes" style="max-height: 100%;">
			<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
				<%= link_to new_institute_grade_path(@institute) do %>
					<div class="pull-right add-member">
						<span>Add Classes</span><i class="material-icons">&#xE7FE;</i>
					</div>
				<% end %>
				<div class="clearfix mar-btm"></div>	
			<% end %>
			
			<ul class="list-unstyled">
				<% if(!@grades.blank?) %>
					<% @grades.each do |grade| %>
						<li class="find-teacher-list find-tab-teacher-list" style="margin-bottom:10px;position:relative;">
								
							<h6 class="teachers-list-heading-inner" style="background: #d1cece;margin: 0;padding: 10px; color: #dd223d;">
								<%= grade.custom_name_for_institute(@institute) %>																		
								<i class="material-icons arrow-up-icon pull-right" style="margin-top:-5px;">&#xE316;</i>
							</h6>

							<div class="container-width classRoute class-tab-students-list-custom" style="display: none; box-shadow:rgb(175, 172, 172) 1px 1px 10px;margin-bottom:10px; padding: 4px;">
								
								<ul class="list-unstyled index-conversation-modal student-manage-page" style="box-shadow: none;    max-height: 200px !important;overflow: scroll;">
									<% sections = grade.grades_sections.where(institute_id: @institute.id).map(&:section) %>
									<% if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
										<%= link_to new_institute_grade_section_path(@institute, grade) do %>
											<div class="pull-right add-member">
												<span>Add Section</span><i class="material-icons">&#xE7FE;</i>
											</div>
										<% end %>
										<div class="clearfix"></div>	
									<% end %>
									
									<% if(!sections.blank?) %>
										<% sections.each do |section| %>
											<li class="link-button">
												<%= link_to "Section #{section.section_name}", institute_grade_section_path(@institute, grade, section) %>
											</li>
										<% end %>
									<% else %>
										
										<div class="clearfix mar-btm"></div>	
										<h1 class="nothing-posted"> No Section added yet ! </h1>					
									<% end %>
								</ul>	
							</div>
						</li>		
					
					<% end %>

				<% else %>
					<div class="clearfix"></div>	
					<h1 class="nothing-posted"> No Classes added yet ! </h1>					
				<% end %>
				
			</ul>
		</div>
	</div>
</div>			
<script>
	var randomColors = ["#35a5a5",'#8cc4c4','#8b5861',"#d7b26f"];
	$(".ch-thumb").each(function(index) {
        var len = randomColors.length;
        var randomNum = Math.floor(Math.random()*len);
        $(this).css("backgroundColor",randomColors[randomNum]);
        randomColors.slice(randomNum, 1);
    });
    
	$(document).one("turbolinks:load", function(){
		$(".classRoute").parents("div.wrapper").find(".navbar-default").css("box-shadow", "none");
		
	});
	$('.search-conversation-admin-page').on("keyup keydown", function() {
		
	    var value = $(this).val();
	    if(value){
	    	$(".admin-manage-page").hide().filter(function () {
				if($(".media-heading", this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0 || $(".role-small", this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0){					
					return true;
				}else{
					return false;
				}			    
			}).show();
	    }else{
	    	$(".admin-manage-page").show();
	    }    
	});
	$('.search-conversation-teacher-page').on("keyup keydown", function() {
		
	    var value = $(this).val();
	    if(value){
	    	$(".teacher-manage-page").hide().filter(function () {
				if($(".media-heading", this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0 || $(".role-small", this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0 ) {					
					return true;
				}else{
					return false;
				}			    
			}).show();
	    }else{
	    	$(".teacher-manage-page").show();
	    }    
	});
	$('.search-conversation-student-page').on("keyup keydown", function() {
		
	    var value = $(this).val();
	    if(value){
	    	$(".student-manage-page li").hide().filter(function () {
				var mediaHeading = $(this).find(".media-heading");
				var roleSmall = $(this).find(".role-small");
				if(mediaHeading.text().toLowerCase().indexOf(value.toLowerCase()) >= 0 || roleSmall.text().toLowerCase().indexOf(value.toLowerCase()) >= 0 ){	
					if(mediaHeading.parents('.class-tab-students-list-custom').css("display") == "none"){
						mediaHeading.parents('.class-tab-students-list-custom').css("display", "block");
					}				
					return true;
				}else{
					return false;
				}			    
			}).show();
	    }else{
	    	$(".student-manage-page li").show();
			$('.class-tab-students-list-custom').css("display", "none");
	    }    
	});
	
</script>