config/routes.rb
Rails.application.routes.draw do
  
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  	root to: "conversations#index"
    get "help" => "home#help"
    get "download_institute_data_template" => "home#download_institute_data_template"
  
  	devise_for :users, controllers: { sessions: 'my_devise/sessions', registrations: 'my_devise/registrations', omniauth_callbacks: 'my_devise/omniauth_callbacks', passwords: 'my_devise/passwords', unlocks: 'my_devise/unlocks' }
    
  	resources :users do
  		member do 
  			get :complete_registration 
  			post :complete_registration 
  		end	
  	end
  	
  	resources :institutes do
  		member do
  			get "add_new_member"
  			post "add_new_member"
        
        get "add_new_student"
        post "add_new_student"

        get "add_new_parent"
        post "add_new_parent"

        get "add_new_teacher"
        post "add_new_teacher"

        get "add_new_staff"
        post "add_new_staff"

        get "give_admin_right"
        post "give_admin_right"

        get "revoke_admin_right"
        post "revoke_admin_right"
  		end

      resources :events

      resources :timetable_slots

      resources :notices

      resources :attendance_records do
        collection do
          get "section_attendance_record_form"
        end
      end

      resources :grades do
        collection do
          get "add_new_grade"
          post "add_new_grade"
        end
        resources :sections do
          collection do
            get "add_new_section"
            post "add_new_section"
          end

          member do 
            get "set_classteacher"
            post "set_classteacher"
          end 

          resources :subjects do
            collection do
              get "add_new_subject"
              post "add_new_subject"
            end 

            member do 
              get "set_subject_teacher"
              post "set_subject_teacher"
            end 
          end

        end
      end
  	end

    resources :conversations do
      resources :messages do
        member do
          post "set_seen_user_id"
          get "seen_by_users"

          post "set_acted_user_ids"
          get "acted_by_users"
        end
      end
      member do
        get "remove_participants"
        post "remove_participants"
        post "add_message_category"
        delete "delete_message_category"
      end

      collection do
        get "new_group"
        post "new_group"
        get "homework"
      end  
    end

    resources :attachments do
      member do
        get "download"
      end
    end

  	resources :android_devices
    resources :ios_devices
    resources :web_notification_subscriptions
    resources :apple_web_notification_subscriptions

    scope format: false, constraints: {website_push_id: /[a-zA-Z0-9\._-]+/} do
    	post '/:version/pushPackages/:website_push_id' => 'safari_web_push#send_push_package'
	    post '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#register_device'
	    delete '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#unregister_device'
	    post '/:version/log' => 'safari_web_push#log'
	  end

    mount ActionCable.server => '/cable'
   	
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :set_conversation, except: [:index, :new, :create, :new_group, :add_new_member, :homework] 

	def set_conversation
		@conversation = Conversation.find_by(id: params[:id])
		if(@conversation.blank?)
			head :ok
			return
		end
	end

	def index

		if(!user_signed_in?)
			render "home/index", layout: "home"
			return
		end

		@conversations = current_user.participating_conversations.order(updated_at: :desc)
			
		inbox_conversations_array = []
		@conversations.each do |conversation|
			if(conversation.is_group != true and !conversation.messages.last.blank? and conversation.messages.last.creator_id != current_user.id)	
				inbox_conversations_array << conversation
			end
		end

	 	sent_conversations_array = []
	 	@conversations.each do |conversation|
			if((!conversation.messages.last.blank? and conversation.messages.last.creator_id == current_user.id and conversation.is_group == false) or (conversation.last_message_id.blank? and conversation.creator_id == current_user.id and conversation.is_group == false)) 
				sent_conversations_array << conversation
			end
		end

		group_conversations_array = []
		@conversations.each do |conversation|
			if(conversation.is_group == true)
				group_conversations_array << conversation
			end	
		end

		@inbox_conversations = Conversation.where(id: inbox_conversations_array.map(&:id)).order(updated_at: :desc)
		@sent_conversations = Conversation.where(id: sent_conversations_array.map(&:id)).order(updated_at: :desc)
		@group_conversations = Conversation.where(id: group_conversations_array.map(&:id)).order(updated_at: :desc)
		
		@unread_conversation_ids_array = []
		@inbox_conversations.each do |conversation|
			conversation_participant_model = conversation.get_conversation_participant_model_for_participant(current_user)
			unread_received_messages = conversation.messages.where("is_seen_by_all_participants != ? and created_at > ? and creator_id != ?", true, conversation_participant_model.created_at, current_user.id)
			unread_received_messages.each do |message|
				seen_user_ids_array = message.seen_user_ids.split(", ").map{|id| id.to_i}.uniq
				if(!seen_user_ids_array.include?(current_user.id))
					@unread_conversation_ids_array << conversation.id
					break
				end
			end
		end
		@unread_group_conversation_ids_array = []
		@group_conversations.each do |conversation|
			conversation_participant_model = conversation.get_conversation_participant_model_for_participant(current_user)
			unread_received_messages = conversation.messages.where("is_seen_by_all_participants != ? and created_at > ? and creator_id != ?", true, conversation_participant_model.created_at, current_user.id)
			unread_received_messages.each do |message|
				seen_user_ids_array = message.seen_user_ids.split(", ").map{|id| id.to_i}.uniq
				if(!seen_user_ids_array.include?(current_user.id))
					@unread_group_conversation_ids_array << conversation.id
					break
				end
			end
		end

		@homework_conversations = @conversations.where("message_categories LIKE ?", "Homework%")
		homework_messages_array = []

		if(current_user.role.include?("Teacher"))
			if(!@homework_conversations.blank?)
				@homework_conversations.each do |conversation|					
				    conversation_homework_messages = conversation.messages.where(category: "Homework", creator_id: current_user.id).order(created_at: :desc)
					if(!conversation_homework_messages.blank?)
						conversation_homework_messages.each do |message|
							homework_messages_array << message
						end	
					end
				end
	    	end
	    else
	    	if(!@homework_conversations.blank?)
				@homework_conversations.each do |conversation|					
				    conversation_homework_messages = conversation.messages.where(category: "Homework").order(created_at: :desc)
					if(!conversation_homework_messages.blank?)
						conversation_homework_messages.each do |message|
							homework_messages_array << message
						end	
					end
				end
	    	end	
		end

		if(params[:page] and params[:page].to_i >= 2)
			@inbox_conversations = @inbox_conversations.page(params[:page]).per(10)
			@sent_conversations = @sent_conversations.page(params[:page]).per(10)
			@group_conversations = @group_conversations.page(params[:page]).per(10)
			@homework_messages = Message.where(id: homework_messages_array.map(&:id)).page(params[:page]).per(10)
		else
			@inbox_conversations = @inbox_conversations.page(1).per(10)
			@sent_conversations = @sent_conversations.page(1).per(10)
			@group_conversations = @group_conversations.page(1).per(10)
			@homework_messages = Message.where(id: homework_messages_array.map(&:id)).page(1).per(10)
		end
		
		@principals = @institute.get_members_with_given_roles(["Principal"])
		@admins = @institute.get_members_with_given_roles(["Institute Admin"])
		@teachers = @institute.get_members_with_given_roles(["Teacher"])

		if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) 
			
			@grades = @institute.grades
			@institutes_grades_sections_models = @institute.institutes_grades_sections_models

            @teachers = @institute.get_members_with_given_roles(["Teacher"]) 
                
			render "admin_index" 
			return

		end

		if(current_user.role.include?("Teacher"))
			@all_section_member_models = current_user.members_sections
			@grades = @all_section_member_models.map(&:grade).uniq
			@assigned_classteacher_grades_sections_model = current_user.assigned_classteacher_grades_sections_models.first
			if(!@assigned_classteacher_grades_sections_model.blank?)
				@todays_attendance_record = current_user.created_attendance_records.find_by(date: Date.today)

				@grade = @assigned_classteacher_grades_sections_model.grade
				@section = @assigned_classteacher_grades_sections_model.section
				@class_students =  @section.get_members_with_given_roles_for_institute_and_grade_with_role(@institute, @grade, "Student")
			end

			render "teacher_index"
			return
		end

		if(current_user.role == "Student" or current_user.role == "Parent")
			@all_section_member_models = current_user.members_sections
			@grades = @all_section_member_models.map(&:grade).uniq
			
			render "student_index"
			return
		end
	end
	
	def new
		@principals = @institute.get_members_with_given_roles(["Principal"])
		@admins = @institute.get_members_with_given_roles(["Institute Admin"])
		@teachers = @institute.get_members_with_given_roles(["Teacher"])
		if(current_user.role.include?("Principal") or current_user.role.include?("Institute Admin"))			
			@institutes_grades_sections_models = @institute.institutes_grades_sections_models
		end

		if(current_user.role == "Teacher")
			@teaching_section_subject_models = current_user.teaching_sections_subjects_models
		end
	end

	def create
		
		if(!params[:participant_ids].blank?)
			@participants = User.where(id: params[:participant_ids]).to_a if !params[:participant_ids].blank?
			if(!@participants.blank?)
				if(params[:conversation_id].blank?)
						
					old_conversations = current_user.participating_conversations
			
					old_conversations.each do |conversation|
						if(conversation.is_custom_group == true and conversation.check_if_conversation_is_between_users(@participants + [current_user]))
							
							@conversation = conversation
							(@participants - @conversation.participants).each do |participant|
								@conversation.add_participant(participant.id, current_user.id)
							end
							
						end
					end
					if(@conversation.blank?)
						@conversation = current_user.created_conversations.create(is_open_group: true)
						@participants.each do |participant|
							@conversation.add_participant(participant.id, current_user.id)	
						end	
					end

					if(!params[:message].blank? or !params[:attached_files].blank?)
						@new_message = @conversation.messages.create(content: params[:message], category: params[:message_category], creator_id: current_user.id)
		
						attached_files = params[:attached_files]
						if (!attached_files.blank?)
							attached_files.each do |file|
								new_attachment = @new_message.attachments.new()
								new_attachment.media = file

								if(!params[:attachment_category].blank?)
									new_attachment.category = params[:attachment_category] 
									if( "Image, Video, Link".include?(params[:attachment_category]) )
										@conversation.message_categories = "" if @conversation.message_categories.blank?
										if(!@conversation.message_categories.include?(params[:message_category]))
											@new_message.update(category: "Media")	
										end
									else	
										@new_message.update(category: params[:attachment_category])	if @new_message.category != params[:attachment_category]
									end	
								end

								new_attachment.save
							end
						end
						@conversation.update_attributes(last_message_id: @new_message.id)
						render_to_string "messages/create.js"
					end

					redirect_to conversation_path(@conversation), format: :js
					
				else
					@conversation = current_user.participating_conversations.where(id: params[:conversation_id]).first
					if(!@conversation.blank?)
						if(!(@participants - @conversation.participants).blank?)
							(@participants - @conversation.participants).each do |new_participant|
								@conversation.add_participant(new_participant.id, current_user.id)
							end
							redirect_to conversation_path(@conversation), format: request.format
						else
							redirect_to conversation_path(@conversation)
							return
						end
					else
						
					end
				end				
			else
				
			end
		else
		
		end
		
	end

	def new_group
		if(request.get?)
			@principals = @institute.get_members_with_given_roles(["Principal"])
			@admins = @institute.get_members_with_given_roles(["Institute Admin"])
			@teachers = @institute.get_members_with_given_roles(["Teacher"])
			
			render "new_group"

		elsif(request.post?) 
			if(!params[:conversation_name].blank?)

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_contact.html.erb
<%= link_to user_path(contact) do %>
	<div class="well well-sm">
	
		<div class="media jumbotron-media">
			<div class="media-left media-middle">
				
				<img src="<%= contact.profile_picture.media.url(:thumb) %>" class="img-rounded img-xs">
				
			</div>
			<div class="media-body media-middle">
				<h5 class="media-heading student-name-in-message"><%= contact.first_name %> <%= contact.last_name %></h5>

				<small class="role-small"><%= contact.details %></small>
				
			</div>				
		</div>
		
	</div>

<% end %>

app/views/conversations/_group_small.html.erb
<div class="media mar-btm open-contact-on-click-element-parent">
	<div class="media-left media-middle open-contact-on-click-element">
		<img src ="<%= group.get_conversation_image_url_to_show_to_user(current_user, :thumb) %>" class="media-object img-circle <%= group.id %>" >
	</div>
	<div class="media-body media-middle next-page-link" data-request-type="GET" data-next-page-link-address="<%= conversation_path(group) %>">
		<h4 class="media-heading"> <span class="media-heading-content"><%= group.get_conversation_name_to_show_to_user(current_user) %> </span></h4>
		<p class="text-muted"> <%= group.participants.length %> Participants</p>	
	</div>
	<div class="icon-short-profile-modal-main-div"  style="display:none;">
		<ul class="icon-short-profile-modal list-inline display_inline text-center">
			<li>
				<%= link_to conversation_path(group) do %>
					<i class="material-icons">&#xE0C9;</i></li>
				<% end %>
				
			<li>
				<%= link_to edit_conversation_path(group) do %>
					<i class="material-icons">&#xE89E;</i></li>
				<% end %>	
		</ul>
	</div>
</div>

app/views/conversations/delete_message_category.js.erb
$(".message-category").val("");
$("li a[href='#all-<%=params[:message_category]%>']").remove();
$("#all-<%=params[:message_category]%>").remove();
$("#<%=params[:message_category]%>-message-category-input").remove();
$("#<%=params[:message_category]%>-attachment-li").remove();
$(".<%=params[:message_category]%>-Message-category-remove-link-li").remove();


$(".chat-show-tabs-upper-div").find("li").removeClass("active").find("a").attr("aria-expanded", false);
$(".admin-home-content").find("div[id^=all]").removeClass("active");
$('a[href="#all-Messages"]').parents("li").addClass("active").find("a").attr("aria-expanded", true);
$('div[id="all-Messages"]').addClass("active");

app/views/conversations/edit.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top main-app-header">
	<div class="container-fluid">
		<div class="navbar-header main-app-conversation-new-header pull-left">
			<a class="mybtn btn btn-link btn-xs pull-left" href="<%= conversation_path(@conversation) %>"><i class="material-icons">&#xE317;</i></a>
		</div>
		<ul class="nav navbar-nav navbar-right main-app-show-header pull-right display_inline">
			<% if(@conversation.can_user_add_participants(current_user)) %>
				<li>
					<%= link_to new_conversation_path(conversation_id: @conversation.id) do %>
						<i class="material-icons">&#xE7FE;	</i>
					<% end %>
				</li>			
			<% end %>
			<li class="dot-menu-show dropdownToggle"><span id="dropdownToggle"></span></li>
		</ul>
		<ul class="dropdownMenu">
			<% if(user_signed_in?) %>
				<li class="text-center">
					<%= link_to user_path(current_user) do %>
						<img src="<%= @current_user.profile_picture.media.url(:thumb) %>" class="img-circle img-sm">
					<% end %>
				</li>
				<li class="text-center">
					<%= link_to user_path(current_user) do %>
						<span>My Profile</span>
					<% end %>
				</li>
				<li class="text-center">
					<%= link_to "Logout", destroy_user_session_path, method: :delete %>
				</li>
				
			<% end %>

			
		</ul>
		
	</div>	
</nav>
<div class="container-width conversation-user-container">
	<div class="row new-group-row">
		<div class="col-lg-12 text-center">
			<div id="new-group-profile-picture-target">
				<div id="new-group-profile-picture-inner-target" class="new-group-profile-picture-inner-target">
					<img src="<%= @conversation.get_conversation_image_url_to_show_to_user(current_user, :thumb) %>" class="media-object" >
				</div>	
			</div>			
		</div>
		<div class="detect-div"></div>
		<div class="text-muted new-group-input group-name">
			<h4 style="margin:0;"><%= @conversation.get_conversation_name_to_show_to_user(current_user) %></h4>
			<p> Created <%= show_human_time(@conversation.created_at) %> </p>	
		</div>		
	</div>
</div>	
<% if(@conversation.can_user_add_participants(current_user)) %>
	
	<div class="media mar-btm">
		<div class="media-left media-middle">
			<%= link_to new_conversation_path(conversation_id: @conversation.id) do %>
				<i class="material-icons">&#xE7FE;</i>
			<% end %>		
		</div>
		<div class="media-body media-middle">
			<%= link_to new_conversation_path(conversation_id: @conversation.id) do %>
				Add New Participant
			<% end %>
		</div>
	
	</div>

	<div class="media mar-btm">
		<div class="media-left media-middle">
			<%= link_to add_new_member_conversations_path do %>		
				<i class="material-icons">&#xE7FE;</i>
			<% end %>		
		</div>
		<div class="media-body media-middle">
			<%= link_to add_new_member_conversations_path do %>		
				Create New Contact
			<% end %>
		</div>
	
	</div>

<% end %>

<div class="container">
	<% if(!@participants.blank?) %>
		<% @participants.each do |participant| %>
			<%= render partial: "contact", locals: {contact: participant} %>
		<% end %>
	<% end %>
</div>	

<script>
	$(document).bind('scroll', function(){
		fixName();
	});
	function fixName() {
		var buttonDivConversationShow = $('.conversation-user-container').find('.detect-div');
		if(buttonDivConversationShow.offset()){
			var windowTop = $(window).scrollTop();
			var divTop = $('.conversation-user-container').find('.detect-div').offset().top - 130;
			if (windowTop > divTop) {				
				$('.group-name').addClass('stick-group-name');					
			} else {
				$('.group-name').removeClass('stick-group-name');
			}
		}			
	}

</script>

app/views/conversations/new_group.html.erb
<% content_for :heading do %>
  <a class="mybtn btn btn-link btn-xs pull-left" href="/"><i class="material-icons">&#xE88A;</i></a>
  New Group
<% end %>

<% if(!current_user.role.include?("Student") and !current_user.role.include?("Parent")) %>
	
	<div class="container-width conversation-new-container new-group-member-container" style="margin-top:100px;margin-bottom: 60px;">
		<%= form_tag new_group_conversations_path, method: :post, remote: true, id: "new-group-form" do %>
			<%= hidden_field_tag :step, "1" %>
			
			<div class="row new-group-row">
				<div class="col-lg-12 text-center">
					<div id="new-group-profile-picture-target" style="max-width:320px;margin:0 auto;position:relative;">
						<div id="new-group-profile-picture-inner-target" class="new-group-profile-picture-inner-target">
							<%= image_tag "default_profile_picture.png", class: "img-responsive img-rounded" %> 
						</div>	
						<label class="file-label" for="new-group-profile-pic-uploadBtn">
							<span class="file-label-class"><i class="material-icons">&#xE439;</i></span>
							<%= file_field_tag :banner_image, :id=>"new-group-profile-pic-uploadBtn" %>
						</label>
					</div>			
				</div>
				<div class="form-group new-group-input" style="max-width:320px;margin:0 auto;">		
				
					<%= text_field_tag :conversation_name, nil, required: true, placeholder: "Group Name", class:"form-control" %>
				</div>
				<div class="nothing-posted" style="max-width: 400px; margin: 0 auto; margin-top: 10px;">
					<span style="vertical-align: middle; margin-right: 4px;">Who can post Messages</span><br>
					Everyone <%= radio_button_tag :is_open_group, true, true, class: "open-group-input" %>
					Group Admins <%= radio_button_tag :is_open_group, false, false, class: "open-group-input" %>
				</div>

			</div>

			<div class="attendance-body" style="display: none; max-width: 400px; margin: 0 auto;padding: 2px;">
				
					<div class="pull-right form-group has-feedback" style="width: 100%; margin-top: 10px;">
						<input type="text" class="form-control search-conversation-new-group-page" name="search" placeholder="Search..." id="search-conversation-new-group" autocomplete="off">
					</div>
				
				<div class="clearfix"></div>
				<ul class="list-inline list-conversation-group-search" style="margin:10px;">
					
					<div class="clearfix mar-btm"></div>
					<ul class="list-unstyled teachers-list new-group-class" style="overflow: hidden; ">
						<li>
							<h6 class="teachers-list-heading" style="padding: 2px;"><span class="checkbox-counter" style="color:#fff;margin-left:0;line-height:4;">Select</span> <span style="font-size:11px;color:#fff;">Group Admins</span><i class="material-icons arrow-up-icon pull-right" style="margin-top: 9px;">&#xE316;</i></h6>
							<div class="container-width classRoute" style="display: block;overflow: scroll;max-height: 300px;">
								<ul class="list-unstyled index-conversation-modal" style="margin-bottom: 30px;">
									<% if(!@teachers.blank?) %>
										<% @teachers.each do |teacher| %>															
											<li>
												<div class="well well-sm">
													<div for="contact-new-group-<%= teacher.id %>" class="modal-label" style="vertical-align: middle;">
														<%= check_box_tag "admin_ids[]", teacher.id, false,class:"contact-new-group-page", id:"contact-new-group-#{teacher.id}" %>
												
														<div class="media jumbotron-media">
															<div class="media-left media-middle">
																
																<img src="<%= teacher.profile_picture.media.url(:thumb) %>" class="img-rounded img-xs">
																
															</div>
															<div class="media-body media-middle">
																<h5 class="media-heading student-name-in-message"><%= teacher.first_name %> <%= teacher.last_name %></h5>

																<small class="role-small"><%= teacher.details %></small>
																
															</div>				
														</div>
														<span class="uncheckbox-style-block uncheckbox-style-block-<%= teacher.id %>"></span>		
														<span class="checkbox-style-block checkbox-style-block-<%= teacher.id %>"></span>
													</div>
												</div>	
											</li>															
										<% end %>
									<% else %>
										<%= link_to add_new_staff_institute_path(@institute, role: "Teacher") do %>
											<div class="pull-right add-member">
												<span>Add Teacher</span><i class="material-icons">&#xE7FE;</i>
											</div>
										<% end %>
										<div class="clearfix"></div>
										<h1 class="nothing-posted"> No Teachers added yet ! </h1>		
									<% end %>									

									<% if(!@admins.blank?) %>
										<% @admins.each do |admin| %>				
											<li>
												<div class="well well-sm">
													<div for="contact-new-group-<%= admin.id %>" class="modal-label" style="vertical-align: middle;">
														<%= check_box_tag "admin_ids[]", admin.id, false,class:"contact-new-group-page", id:"contact-new-group-#{admin.id}" %>
												
														<div class="media jumbotron-media">
															<div class="media-left media-middle">
																
																<img src="<%= admin.profile_picture.media.url(:thumb) %>" class="img-rounded img-xs">
																
															</div>
															<div class="media-body media-middle">
																<h5 class="media-heading student-name-in-message"><%= admin.first_name %> <%= admin.last_name %></h5>

																<small class="role-small"><%= admin.details %></small>
																
															</div>				
														</div>
														<span class="uncheckbox-style-block uncheckbox-style-block-<%= admin.id %>"></span>		
														<span class="checkbox-style-block checkbox-style-block-<%= admin.id %>"></span>
													</div>
												</div>	
											</li>
										
										<% end %>
									<% else %>	
										<%= link_to add_new_staff_institute_path(@institute, role: "Institute Admin") do %>
											<div class="pull-right add-member">
												<span>Add Admin</span><i class="material-icons">&#xE7FE;</i>
											</div>
										<% end %>
										<div class="clearfix"></div>
										<h1 class="nothing-posted"> No Admins added yet ! </h1>	
									<% end %>														
								</ul>
							</div>
						</li>
					</ul>
				</ul>
			</div>
			<div class="log-out" style="max-width: 400px; margin: 0 auto; margin-top: 10px;">
				<button type="submit" class="btn btn-success" data-disable-with="Creating ...">Create</button>
			
			</div>
			
		<% end %>
	</div>	

	<script>
		$(".modal-label").on("click", function(e){
			
			if($(this).find(".contact-new-group-page").prop("checked") == true){
				$(this).find(".contact-new-group-page").prop("checked", false);
			}else{
				$(this).find(".contact-new-group-page").prop("checked", true);
			}
			
			updateCheckboxCounter();
			
		});
		function updateCheckboxCounter(){
			var len = $("input.contact-new-group-page:checked").length;	
			
			if(len>0){
				$(".checkbox-counter").text(len);
			}else{
				$(".checkbox-counter").text('Select');
			}	
		}
		$('#new-group-profile-pic-uploadBtn').on('change', function(event) {
			var files = event.target.files;
			var image = files[0]
			var reader = new FileReader();
			reader.onload = function(file) {
			  var img = new Image();
			  img.src = file.target.result;
			  img.className = "img-responsive";
			  $('#new-group-profile-picture-inner-target').html(img);
			}
			reader.readAsDataURL(image);
		});	
	
		$(".main-app-conversation-new-header").parents("div.wrapper").find(".navbar-default").css("box-shadow", "none");

		$(".open-group-input").change(function(){
			if($(this).prop("checked") == true && $(this).val() == "true"){
				$(".attendance-body").hide();
				$(".contact-new-group-page").prop("checked", false);
			}
			if($(this).prop("checked") == true && $(this).val() == "false"){
				$(".attendance-body").show();
			}	
		});
	</script>
<% else %>
	You can not create a new group. 
<% end %>