config/routes.rb
Rails.application.routes.draw do
  
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  	root to: "conversations#index"
    get "help" => "home#help"
    get "download_institute_data_template" => "home#download_institute_data_template"
  
  	devise_for :users, controllers: { sessions: 'my_devise/sessions', registrations: 'my_devise/registrations', omniauth_callbacks: 'my_devise/omniauth_callbacks', passwords: 'my_devise/passwords', unlocks: 'my_devise/unlocks' }
    
  	resources :users do
  		member do 
  			get :complete_registration 
  			post :complete_registration 
  		end	
  	end
  	
  	resources :institutes do
  		member do
  			get "add_new_member"
  			post "add_new_member"
        
        get "add_new_student"
        post "add_new_student"

        get "add_new_parent"
        post "add_new_parent"

        get "add_new_teacher"
        post "add_new_teacher"

        get "add_new_staff"
        post "add_new_staff"

        get "give_admin_right"
        post "give_admin_right"

        get "revoke_admin_right"
        post "revoke_admin_right"
  		end

      resources :events

      resources :timetable_slots

      resources :notices

      resources :attendance_records do
        collection do
          get "section_attendance_record_form"
        end
      end

      resources :grades do
        collection do
          get "add_new_grade"
          post "add_new_grade"
        end
        resources :sections do
          collection do
            get "add_new_section"
            post "add_new_section"
          end

          member do 
            get "set_classteacher"
            post "set_classteacher"
          end 

          resources :subjects do
            collection do
              get "add_new_subject"
              post "add_new_subject"
            end 

            member do 
              get "set_subject_teacher"
              post "set_subject_teacher"
            end 
          end

        end
      end
  	end

    resources :conversations do
      resources :messages do
        member do
          post "set_seen_user_id"
          get "seen_by_users"

          post "set_acted_user_ids"
          get "acted_by_users"
        end
      end
      member do
        get "remove_participants"
        post "remove_participants"
        post "add_message_category"
        delete "delete_message_category"
      end

      collection do
        get "new_group"
        post "new_group"
        get "homework"
      end  
    end

    resources :attachments do
      member do
        get "download"
      end
    end

  	resources :android_devices
    resources :ios_devices
    resources :web_notification_subscriptions
    resources :apple_web_notification_subscriptions

    scope format: false, constraints: {website_push_id: /[a-zA-Z0-9\._-]+/} do
    	post '/:version/pushPackages/:website_push_id' => 'safari_web_push#send_push_package'
	    post '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#register_device'
	    delete '/:version/devices/:device_token/registrations/:website_push_id' => 'safari_web_push#unregister_device'
	    post '/:version/log' => 'safari_web_push#log'
	  end

    mount ActionCable.server => '/cable'
   	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, except: :index
  def set_user
    @user = User.find_by(id: params[:id])
  end

  def index
  
  end

  def show
    if(@user.role == "Teacher")
      @assigned_classteacher_grades_sections_model = @user.assigned_classteacher_grades_sections_models.first
      @teaching_sections_subjects_models = @user.teaching_sections_subjects_models
    end

    if(current_user.role == "Parent")
        @children = current_user.children
    end

    if(current_user.role == "Student")
        @father = current_user.father
        @mother = current_user.mother
    end    
  end

  def edit
      if(current_user.role == "Parent")
        @section_member_models = current_user.members_sections
        
        @children = current_user.children
        
      end

      if(current_user.role == "Student")
        section_member_model = current_user.members_sections.first
        grade = section_member_model.grade
        section = section_member_model.section
        parents = section.get_members_with_given_roles_for_institute_and_grade_with_role(@institute, grade, ["Parent"]) 
        @male_parents = parents.map{|parent| parent if parent.gender == "male"}.compact.uniq
        @female_parents = parents.map{|parent| parent if parent.gender == "female"}.compact.uniq
        
        @father = current_user.father
        @mother = current_user.mother
        
      end
  end

  def update
      @user.first_name = params[:first_name] if !params[:first_name].blank?
      @user.last_name = params[:last_name] if !params[:last_name].blank?
      @user.gender = params[:gender] if !params[:gender].blank?
      @user.email = params[:email] if !params[:email].blank?
      @user.isd_code = params[:isd_code] if !params[:isd_code].blank?
      @user.mobile_no = params[:mobile_no] if !params[:mobile_no].blank?
      @user.staff_id = params[:staff_id] if !params[:staff_id].blank?
      @user.roll_no = params[:roll_no] if !params[:roll_no].blank?
      @user.address = params[:address] if !params[:address].blank?
      @user.pincode = params[:pincode] if !params[:pincode].blank?
      @user.date_of_birth = Date.parse(params[:date_of_birth]) if !params[:date_of_birth].blank?
      @user.is_using_transport = params[:is_using_transport]
      if(!params[:father_id].blank?)

          @father = User.find_by(id: params[:father_id])
          if(!@father.blank?)
              @user.father_id = @father.id
              if(@father.child_ids.blank?)
                  @father.child_ids = @user.id.to_s
              else
                  @father.child_ids = @father.child_ids + ", #{@user.id}"
              end
              @father.save
          end
      end
      
      if(!params[:mother_id].blank?)

          @mother = User.find_by(id: params[:mother_id])
          if(!@mother.blank?)
              @user.mother_id = @mother.id
              if(@mother.child_ids.blank?)
                  @mother.child_ids = @user.id.to_s
              else
                  @mother.child_ids = @mother.child_ids + ", #{@user.id}"
              end
              @mother.save
          end
      end
      
      if(!params[:child_ids].blank?)
          @children = User.where(id: params[:child_ids])
          if(!@children.blank?)
              if(@user.child_ids.blank)
                  @user.child_ids = @children.map(&:id).join(", ")
              else
                  @user.child_ids = @user.child_ids + ", " + @children.map(&:id).join(", ")
              end

              if(@user.gender == "male")
                  @children.each do |child|
                      child.update(father_id: @user.id)
                  end
              end
              if(@user.gender == "female")
                  @children.each do |child|
                      child.update(mother_id: @user.id)
                  end
              end
          end
         
      end
      @user.save
      if(!params[:profile_picture].blank?)
        @user.profile_picture.media = params[:profile_picture]
        @user.profile_picture.save 
      end
      redirect_to user_path(@user)
  end

  def destroy
    if(!@user.blank?)
        @user.destroy
        hash_url = ""
        if(@user.role.include?("Institute Admin") or @user.role.include?("Principal"))
          hash_url = "#all-admins"
        elsif(@user.role.include?("Teacher"))
          hash_url = "#all-teachers"
        else
          hash_url = "#all-students"
        end
        redirect_to institute_path(@institute) + hash_url
    else

    end
        
  end

  def complete_registration
    if(request.get?)
      render layout: "devise"
    elsif(request.post?)
      if(!@user.blank?)
        if(params[:role] == "Institute Admin" or params[:role] == "Principal")
          @user.update(role: params[:role], is_registration_complete: true)
          if(!params[:profile_picture].blank?)
            @user.profile_picture.media = params[:profile_picture]
            @user.profile_picture.save 
          end
          
          if(!params[:institute_name].blank?)
            @institute = @user.created_institutes.create(institute_name: params[:institute_name])
            if(!params[:institute_latitude].blank? and !params[:institute_longitude].blank?)
              @institute.create_location(latitude: params[:institute_latitude], longitude: params[:institute_longitude])
            end
            @institute_conversation = @user.created_conversations.create(conversation_name: params[:institute_name].capitalize.truncate(50), institute_id: @institute.id, is_custom_group: false, message_categories: "")
            
            if(!params[:institute_data_file].blank?)

              @institute_data_file = @institute.create_institute_data_file(media: params[:institute_data_file])
              
              require "spreadsheet"

              data_file = Spreadsheet.open(@institute_data_file.media.path)
              
              class_sheet = data_file.worksheet("Classes")
              if(!class_sheet.blank?)
                class_sheet_fields = class_sheet.row(0)
                section_names = class_sheet_fields[3..(class_sheet.rows.length - 1)]
                class_sheet.rows[1..(class_sheet.rows.length - 1)].each do |class_row|
                  
                  class_name = class_row[0]
                  grade = Grade.find_by(grade_name: class_name)
                  if(grade.blank?)
                    grade = Grade.create(grade_name: class_name)
                  end
                  
                  class_offered = class_row[1]

                  if(!class_offered.blank?)
                    class_custom_name = class_row[2]
                    
                    @institute.institutes_grades.create(custom_grade_name: class_custom_name, grade_id: grade.id, creator_id: current_user.id)
                    section_names.each do |section_name|
                      if(!section_name.blank?)
                        section = Section.find_by(section_name: section_name.split(" ").last)
                        if(section.blank?)
                          section = Section.create(section_name: section_name.split(" ").last)
                        end
                        if(!class_row[class_sheet_fields.index(section_name)].blank?)
                          
                          grade_section_model = @institute.institutes_grades_sections_models.create(grade_id: grade.id, section_id: section.id, creator_id: current_user.id) if !grade.blank? and !section.blank?
                          section_conversation = current_user.created_conversations.create(conversation_name: "#{grade.custom_name_for_institute(@institute)} #{section.section_name}".truncate(30), institute_id: @institute.id, grade_id: grade.id, section_id: section.id, message_categories: "Homework", is_custom_group: false) if !grade.blank? and !section.blank?
                        end
                      end
                      
                    end
                  end
                end
              else

              end

              teachers_sheet = data_file.worksheet("Teachers")
              if(!teachers_sheet.blank?)
                teacher_fields = teachers_sheet.row(0)
                teachers_sheet.rows[1..(teachers_sheet.rows.length-1)].each do |teacher_row|
                  if(!teacher_row.blank?)
                    first_name = teacher_row[0]; first_name = first_name.capitalize if !first_name.blank?
                    last_name = teacher_row[1]; last_name = last_name.capitalize if !last_name.blank?
                    email = teacher_row[2]
                    mobile_no = teacher_row[3]; mobile_no = mobile_no.to_i.to_s if !mobile_no.blank?
                    password = teacher_row[4]; password = password.to_i if password.is_a?(Float); password = password.to_s if !password.blank?; password = Random.new.rand(1000..9999).to_s if password.blank?
                    gender = teacher_row[5]
                    address = teacher_row[6]
                    pincode = teacher_row[7]
                    staff_id = teacher_row[8]; staff_id = staff_id.to_i if staff_id.is_a?(Float); 
                    classteacher_grade_name = teacher_row[9]
                    classteacher_section_name = teacher_row[10]
                    if(!first_name.blank? or !last_name.blank? or !email.blank? or !mobile_no.blank?)
                      staff = User.where(email: email).first if !email.blank?
                      staff = User.where(mobile_no: mobile_no) if email.blank? and !mobile_no.blank?
                      if(staff.blank?)
                        staff = User.new(role: "Teacher")
                        staff.password = password
                        staff.first_name = first_name
                        staff.last_name = last_name
                        staff.mobile_no = mobile_no
                        staff.isd_code = "91"
                        staff.email = email

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/complete_registration.html.erb
<%= link_to destroy_user_session_path, method: :delete do %>
	<button type="button" class="pull-right btn btn-danger" style="padding:10px;margin-right:10px;color:#fff;background:#2ad; border:none;">LogOut</button>
<% end %>
<div class="container" style="margin-top:20px;">
	<div class="row" style="max-width:700px;margin:0 auto;">
		<%= form_tag complete_registration_user_path(@user), method: :post, multipart: true, remote: true, :class=>"form-complete-register", :id => "form-complete-register", "autocomplete"=>"off" do %>
			<div class="col-lg-12 text-center">
				<div id="user-profile-picture-target">
					<div id="user-profile-picture-inner-target" class="user-profile-picture-inner-target">
						<img src="<%= current_user.profile_picture.media.url(:thumb) %>" class="img-circle"> 
						
					</div>

					<label class="file-label" for="profile-pic-uploadBtn">
						<span class="file-label-class"><i class="material-icons">&#xE439;</i></span>
						<%= file_field_tag :profile_picture, :id=>"profile-pic-uploadBtn" %>
					</label>
				</div>
				<span style="font-size:20px;"><%= @user.first_name %> <%= @user.last_name %></span>			
			</div>
			<div class="col-lg-12 text-center">
				<h3 class="text-muted text-left">Complete your Institute Registration</h3>
				<div class="form-group">
					<%= text_field_tag :institute_name, nil , id: "pac-input", class: "controls form-control", placeholder: "My Institute name", required: true %>
				</div>
				<div id="map"></div>
				<div class="form-group">
					<%= select_tag :role, options_for_select([["My role", ""], ["Principal", "Principal"], ["Institute Admin", "Institute Admin"], ["Teacher", "Teacher"], ["Student", "Student"], ["Parent", "Parent"]],[@user.role, @user.role]), required: true, id: "role-input",class: "form-control"  %>
					<br>
					<%= link_to :download_institute_data_template, target: "_blank" do %>
						<div class="form-control add-member pull-left" style="width: 50%">
							Download Data File
						</div>
					<% end %>
					
					<div class="form-control add-member pull-right" style="width: 50%">
						<label for="institute-data-uploadBtn">
							<span id="institute-data-file-text"> Upload Data File </span>
							<%= file_field_tag :institute_data_file, accept: ".xls", :id=>"institute-data-uploadBtn", style: "display: none" %>
						</label>
						
					</div>
				</div>
				<%= hidden_field_tag :institute_latitude, nil, id: "institute_latitude-field" %>
				<%= hidden_field_tag :institute_longitude, nil, id: "institute_longitude-field" %>
				<br>
				
				<div class="form-group">
					<%= text_field_tag :institute_contact_info, nil, placeholder: "Email or Mobile no of Institute Contact Person", id: "school_contact_info-input",class: "form-control", style: "display: none" %>
				</div>
				
			</div>
			<div class="text-center col-md-6 col-md-offset-3">
				<div class="form-group form-button-register">
					<%= button_tag(type:"submit", class: "form-control btn btn-login", data: {disable_with: "Saving"}) do %>
						Save
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>	

<script>
	$(document).one("ready turbolinks:load", initMap);

	<% if(["Teacher", "Student", "Parent"].include?(@user.role)) %>
		$("#school_contact_info-input").show();
		$("#school_contact_info-input").attr("required", true);
	<% end %>

	$("#role-input").change(function(){
		if($(this).val() == ""){
			
			$("#school_contact_info-input").hide();
			$("#school_contact_info-input").attr("required", false);		
			
		}
		if($(this).val() == "Institute Admin" || $(this).val() == "Principal"){
			
			$("#school_contact_info-input").hide();
			$("#school_contact_info-input").attr("required", false);
		}

		if($(this).val() == "Teacher" || $(this).val() == "Student" || $(this).val() == "Parent"){
			
			$("#school_contact_info-input").show();
			$("#school_contact_info-input").attr("required", true);
		}
	});

	function initMap() {
		
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 28.6139, lng: 77.2090},
          zoom: 13
        });
        var input = /** @type {!HTMLInputElement} */(
            document.getElementById('pac-input'));

        var types = document.getElementById('type-selector');
        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);
        autocomplete.setTypes(['establishment']);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map,
          anchorPoint: new google.maps.Point(0, -29)
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          marker.setVisible(false);
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            window.alert("Autocomplete's returned place contains no geometry");
            return;
          }

          // If the place has a geometry, then present it on a map.
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);  // Why 17? Because it looks good.
          }
          marker.setIcon(/** @type {google.maps.Icon} */({
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(35, 35)
          }));
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);
          $("#institute_latitude-field").val(place.geometry.location.lat());
          $("#institute_longitude-field").val(place.geometry.location.lng());

          var address = '';
          if (place.address_components) {
            address = [
              (place.address_components[0] && place.address_components[0].short_name || ''),
              (place.address_components[1] && place.address_components[1].short_name || ''),
              (place.address_components[2] && place.address_components[2].short_name || '')
            ].join(' ');
          }

          infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
          infowindow.open(map, marker);
        });
    
    }


	$(function() {
		$('#profile-pic-uploadBtn').on('change', function(event) {
			var files = event.target.files;
			var image = files[0]
			var reader = new FileReader();
			reader.onload = function(file) {
			  var img = new Image();
			  img.src = file.target.result;
			  img.className = "custom-profile-image img-circle";
			  $('#user-profile-picture-inner-target').html(img);
			}
			reader.readAsDataURL(image);
		});
		
		$('#institute-data-uploadBtn').on('change', function(event) {
			var files = event.target.files;
			if(files.length > 0){
				$("#institute-data-file-text").html("Data File Attached !");
			}else{
				$("#institute-data-file-text").html("Upload Data File");
			}
		});
	});	
	
</script>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<% content_for :heading do %>
	<a class="mybtn btn btn-link btn-xs pull-left" href="/"><i class="material-icons">&#xE88A;</i></a>
	<%= @user.first_name %> <%= @user.last_name %>
<% end %>

<div class="container" style="max-width:600px;margin:0 auto;margin-top:90px;">
	<div class="row">
		<div class="user-details">
            <div class="user-image">
                <img src="<%= @user.profile_picture.media.url(:medium) %>" class="img-circle img-xs"%>
            </div>
            <div class="user-info-block">
                <div class="user-heading">
                    <span class="help-block"><%= @user.details %></span>
                    <span><%= @user.gender.capitalize if !@user.gender.blank? %></span>

                </div>
				<div class="user-body" style="margin-bottom: 70px;">
                    <div class="">
                        <div id="information">
                    	
							<div class="personal-infromation">
								<% if(@user.role == "Teacher") %>
	                        		<% if(!@assigned_classteacher_grades_sections_model.blank?) %>
	                        			<p>ClassTeacher of Class <%= @assigned_classteacher_grades_sections_model.grade.grade_name %><%= @assigned_classteacher_grades_sections_model.section.section_name %></p>
	                        		<% end %>
	                        		<% if(!@teaching_sections_subjects_models.blank?) %>
	                        			<p>Teaches <%= @teaching_sections_subjects_models.map{|ss| ss.subject.subject_name}.uniq.join(", ") %> in Class <%= @teaching_sections_subjects_models.map{|ss| ss.grade.grade_name + ss.section.section_name}.uniq.join(", ") %></p>
	                        		<% end %>
	                        	<% end %>
	                        	<% if(user_signed_in? and (@user.id == current_user.id or current_user.role.include?("Principal") or current_user.role.include?("Institute Admin"))) %>
									
									<h4>Personal Information</h4>
									<p>Email Id : <span class="pull-right"> <%= @user.email %> </span></p>
									<p>Mobile no : <span class="pull-right"> <%= @user.mobile_no %> </span></p>
								<% end %>
								
								<% if(user_signed_in? and (@user.id == current_user.id or current_user.role.include?("Principal") or current_user.role.include?("Institute Admin") or current_user.role.include?("Teacher"))) %>
									
									<% if(@user.role == "Student") %>
										<p>Admission Number : <span class="pull-right"> <%= @user.roll_no %> </span> </p>
										<p>Date of Birth : <span class="pull-right"> <%= @user.date_of_birth.strftime('%v') if !@user.date_of_birth.blank? %> </span> </p>
										<% if(@user.id == current_user.id or current_user.role.include?("Principal") or current_user.role.include?("Institute Admin")) %>
											<p>Address : <span class="pull-right"> <%= @user.address %> </span> </p>
											<p>Pin Code : <span class="pull-right"> <%= @user.pincode %> </span> </p>
											<p>Using School Transport ? : <span class="pull-right"> <%= @user.is_using_transport ? "Yes" : "No" %> </span> </p>
										<% end %>
										
										<% if(!@user.father.blank?) %>
											<h4> Father </h4>
											<p><%= render partial: "conversations/contact", locals: {contact: @user.father} %></p>
										<% end %>
										<% if(!@user.mother.blank?) %>
											<h4> Mother </h4>
											<p><%= render partial: "conversations/contact", locals: {contact: @user.mother} %></p>
										<% end %>
									<% end %>
									
									<% if(@user.role == "Parent") %>
										<p>Address : <span class="pull-right"> <%= @user.address %> </span> </p>
										<p>Pin Code : <span class="pull-right"> <%= @user.pincode %> </span> </p>
										<% if(!@user.child_ids.blank?) %>
											<h4> Children </h4>
											<% @user.children.each do |child| %>
												<p><%= render partial: "conversations/contact", locals: {contact: child} %></p>
											<% end %>
										<% end %>
										
										
									<% end %>
									<% if(!@user.role.include?("Student") and !@user.role.include?("Parent")) %>
										<p>Staff ID : <span class="pull-right"> <%= @user.staff_id %> </span> </p>
										<p>Address : <span class="pull-right"> <%= @user.address %> </span> </p>
										<p>Pin Code : <span class="pull-right"> <%= @user.pincode %> </span> </p>

									<% end %>
								<% end %>
								
							</div>	
							<% if(@user.id == current_user.id) %>					
								<p>
									<%= link_to root_path do %>
										My Messages
									<% end %>
								</p>
								<p class="my-classes-teacher">
									<%= link_to institute_grades_path(@institute) do %>
										My Classes
									<% end %>	
								</p>
								<p>
									<%= link_to homework_conversations_path do %>
										My HomeWork
									<% end %>
								</p>							
								<p>
									<%= link_to institute_timetable_slots_path(@institute) do %>
										My Day Plan
									<% end %>
								</p>
							<% end %>	
							
                        </div>
                        <% if(user_signed_in? and (@user.id == current_user.id or current_user.role.include?("Principal") or current_user.role.include?("Institute Admin"))) %>
							<div class="log-out">
								<%= link_to edit_user_path(@user) do %>
									<button type="button" class="btn btn-danger">Edit Profile</button>
								<% end %>
								
							</div>
							<% if(@user.id == current_user.id) %>
								<br>
								<div class="log-out">

									<%= link_to edit_user_registration_path do %>
										<button class="btn btn-danger change-password-btn pull-right"> Change Password </button>
									<% end %>
								</div>
							<% end %>
							<% if(@user.id != current_user.id) %>
								<br>
								<div class="log-out">

									<%= link_to user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete this account ?"} do %>
										<button class="btn btn-danger change-password-btn pull-right"> Delete This Account </button>
									<% end %>
								</div>
							<% end %>
							
						<% end %>
						
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>	
<script>
	$(".my-classes-teacher").click(function(e){
		$(this).find(".arrow-up-icon").toggleClass("arrow-down-icon");
		$(".my-classes-teacher-toggle").slideToggle();
	});
	if($(".inner-toggle-my-teacher-classes").css("display")=="none"){
		$("hr.line-hr").addClass("display_none");
	}
	$(".inner-subject-toggle").click(function(e){
		$(this).toggleClass("arrow-down-icon");
		$(this).parents("ul.my-classes-teacher-toggle li").find("hr").toggleClass("display_none");
		$(this).parents("ul.my-classes-teacher-toggle li").find(".inner-toggle-my-teacher-classes").slideToggle();
	});
</script>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>